# Generated by Django 5.2.14 on 2026-06-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la oficina')),
                ('direccion', models.TextField(blank=True, help_text='Dirección completa de la oficina', verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('responsable', models.CharField(blank=True, help_text='Nombre del encargado de la oficina', max_length=200, verbose_name='Responsable')),
                ('estatus', models.CharField(choices=[('activa', '✅ Activa'), ('inactiva', '⛔ Inactiva')], default='activa', max_length=10, verbose_name='Estatus')),
                ('activa', models.BooleanField(default=True, help_text='Desmarca para desactivar la oficina sin eliminarla', verbose_name='¿Oficina activa?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activa'], name='finanzas_of_activa_7ae135_idx')],
            },
        ),
    ]
