# Generated by Django 5.2.14 on 2026-06-03 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='estatus',
        ),
    ]
