# Generated by Django 5.2.14 on 2026-06-03 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_notificacion'),
        ('finanzas', '0002_remove_office_estatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettlementPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('forma_pago', models.CharField(choices=[('efectivo', '💵 Efectivo'), ('transferencia', '🏦 Transferencia bancaria'), ('cheque', '📄 Cheque'), ('tarjeta_credito', '💳 Tarjeta de crédito'), ('tarjeta_debito', '💳 Tarjeta de débito'), ('deposito', '🏧 Depósito'), ('otro', '🔄 Otro')], default='efectivo', max_length=20, verbose_name='Forma de pago')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedientes.cliente', verbose_name='Cliente')),
                ('expediente', models.ForeignKey(help_text='Expediente relacionado al pago', on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente', verbose_name='Expediente')),
                ('oficina', models.ForeignKey(help_text='Oficina que recibe el pago', on_delete=django.db.models.deletion.PROTECT, to='finanzas.office', verbose_name='Oficina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de Convenio',
                'verbose_name_plural': 'Pagos de Convenios',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha'], name='finanzas_se_fecha_90df30_idx'), models.Index(fields=['forma_pago'], name='finanzas_se_forma_p_83510b_idx'), models.Index(fields=['oficina', 'fecha'], name='finanzas_se_oficina_1827c3_idx')],
            },
        ),
    ]
