# Generated by Django 5.2.14 on 2026-06-03 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_settlementpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del gasto')),
                ('categoria', models.CharField(choices=[('renta', '🏢 Renta'), ('luz', '💡 Luz'), ('agua', '🚰 Agua'), ('internet', '🌐 Internet'), ('telefono', '📞 Teléfono'), ('papeleria', '📎 Papelería'), ('publicidad', '📢 Publicidad'), ('sueldos', '👥 Sueldos'), ('gasolina', '⛽ Gasolina'), ('mantenimiento', '🔧 Mantenimiento'), ('impuestos', '📋 Impuestos'), ('equipo', '💻 Equipo/Cómputo'), ('muebles', '🪑 Muebles'), ('seguros', '🛡️ Seguros'), ('honorarios', '⚖️ Honorarios profesionales'), ('otro', '🔄 Otro')], default='otro', max_length=20, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o detalle del gasto', verbose_name='Descripción')),
                ('proveedor', models.CharField(blank=True, help_text='Nombre del proveedor o beneficiario', max_length=200, verbose_name='Proveedor')),
                ('folio_fiscal', models.CharField(blank=True, help_text='Número de factura o comprobante', max_length=100, verbose_name='Folio fiscal / Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(help_text='Oficina a la que pertenece el gasto', on_delete=django.db.models.deletion.PROTECT, to='finanzas.office', verbose_name='Oficina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha'], name='finanzas_ex_fecha_d08ccb_idx'), models.Index(fields=['categoria'], name='finanzas_ex_categor_c84bdf_idx'), models.Index(fields=['oficina', 'fecha'], name='finanzas_ex_oficina_be1982_idx')],
            },
        ),
    ]
