# Generated by Django 5.2.14 on 2026-06-03 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_notificacion'),
        ('finanzas', '0004_expense'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('monto_convenio', models.DecimalField(decimal_places=2, help_text='Monto total del convenio cerrado', max_digits=12, verbose_name='Monto del convenio')),
                ('porcentaje', models.DecimalField(decimal_places=2, default=5.0, help_text='Ej: 5.00 = 5%', max_digits=5, verbose_name='Porcentaje de comisión')),
                ('monto_comision', models.DecimalField(decimal_places=2, help_text='Calculado automáticamente', max_digits=12, verbose_name='Monto de comisión')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('pagada', '✅ Pagada'), ('cancelada', '❌ Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(help_text='Asesor que recibe la comisión', limit_choices_to={'profile__rol': 'asesor'}, on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to=settings.AUTH_USER_MODEL, verbose_name='Asesor')),
                ('expediente', models.ForeignKey(help_text='Expediente del convenio que generó la comisión', on_delete=django.db.models.deletion.PROTECT, to='expedientes.expediente', verbose_name='Expediente')),
                ('oficina', models.ForeignKey(help_text='Oficina del asesor', on_delete=django.db.models.deletion.PROTECT, to='finanzas.office', verbose_name='Oficina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha'], name='finanzas_co_fecha_ddc369_idx'), models.Index(fields=['estado'], name='finanzas_co_estado_207f6a_idx'), models.Index(fields=['asesor', 'estado'], name='finanzas_co_asesor__999d02_idx'), models.Index(fields=['oficina', 'fecha'], name='finanzas_co_oficina_d14428_idx')],
            },
        ),
    ]
