# Generated by Django 5.2.14 on 2026-06-03 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0005_commission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('puesto', models.CharField(choices=[('administrativo', 'Administrativo'), ('asesor', 'Asesor jurídico'), ('supervisor', 'Supervisor jurídico'), ('contador', 'Contador'), ('recepcionista', 'Recepcionista'), ('auxiliar', 'Auxiliar'), ('director', 'Director'), ('otro', 'Otro')], default='asesor', max_length=30, verbose_name='Puesto')),
                ('periodo_pago', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='quincenal', max_length=15, verbose_name='Periodo de pago')),
                ('salario', models.DecimalField(decimal_places=2, help_text='Salario base del empleado', max_digits=10, verbose_name='Salario')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, help_text='Desmarca cuando el empleado ya no trabaje aquí', verbose_name='¿Activo?')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(help_text='Oficina a la que está asignado', on_delete=django.db.models.deletion.PROTECT, to='finanzas.office', verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de pago')),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('extraordinario', 'Extraordinario'), ('aguinaldo', 'Aguinaldo'), ('prima_vacacional', 'Prima vacacional'), ('bono', 'Bono')], default='quincenal', max_length=20, verbose_name='Período')),
                ('periodo_inicio', models.DateField(blank=True, help_text='Inicio del período que cubre este pago', null=True, verbose_name='Inicio del período')),
                ('periodo_fin', models.DateField(blank=True, help_text='Fin del período que cubre este pago', null=True, verbose_name='Fin del período')),
                ('salario_pagado', models.DecimalField(decimal_places=2, help_text='Monto pagado en este período', max_digits=10, verbose_name='Salario pagado')),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, help_text='Descuentos aplicados (ISR, IMSS, etc.)', max_digits=10, verbose_name='Descuentos')),
                ('total_pagado', models.DecimalField(decimal_places=2, help_text='Salario pagado - descuentos. Calculado automáticamente', max_digits=10, verbose_name='Total pagado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_nomina', to='finanzas.employee', verbose_name='Empleado')),
                ('oficina', models.ForeignKey(help_text='Oficina que realiza el pago', on_delete=django.db.models.deletion.PROTECT, to='finanzas.office', verbose_name='Oficina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nominas_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de Nómina',
                'verbose_name_plural': 'Pagos de Nómina',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['activo'], name='finanzas_em_activo_6d44ee_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['oficina', 'activo'], name='finanzas_em_oficina_3351a7_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['fecha_pago'], name='finanzas_pa_fecha_p_668961_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['empleado', 'fecha_pago'], name='finanzas_pa_emplead_e90d33_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['oficina', 'fecha_pago'], name='finanzas_pa_oficina_057ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['periodo'], name='finanzas_pa_periodo_6e0090_idx'),
        ),
    ]
