# Generated by Django 5.2.14 on 2026-06-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_employee_payroll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='puesto',
            field=models.CharField(choices=[('administrativo', 'Administrativo'), ('asesor', 'Asesor jurídico'), ('supervisor', 'Supervisor jurídico'), ('contador', 'Contador'), ('recepcionista', 'Recepcionista'), ('auxiliar', 'Auxiliar'), ('director', 'Director'), ('otro', 'Otro')], default='administrativo', max_length=30, verbose_name='Puesto'),
        ),
    ]
