# Generated by Django 5.2.14 on 2026-06-03 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0007_alter_employee_puesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('ingreso', '💰 Ingreso'), ('egreso', '💸 Egreso')], max_length=10, verbose_name='Tipo')),
                ('categoria', models.CharField(choices=[('convenio', '🤝 Pago de convenio'), ('cliente', '👤 Pago de cliente'), ('anticipo', '📋 Anticipo'), ('devolucion', '↩️ Devolución'), ('otro_ingreso', '🔄 Otro ingreso'), ('papeleria', '📎 Papelería'), ('gasolina', '⛽ Gasolina'), ('renta', '🏢 Renta'), ('luz', '💡 Luz'), ('agua', '🚰 Agua'), ('internet', '🌐 Internet'), ('telefono', '📞 Teléfono'), ('viaticos', '🚗 Viáticos'), ('comisiones', '👥 Comisiones'), ('honorarios', '⚖️ Honorarios'), ('otro_egreso', '🔄 Otro egreso')], max_length=20, verbose_name='Categoría')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('descripcion', models.TextField(blank=True, help_text='Detalle del movimiento', verbose_name='Descripción')),
                ('referencia', models.CharField(blank=True, help_text='Número de expediente, factura o nota relacionada', max_length=200, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('oficina', models.ForeignKey(help_text='Oficina donde se registra el movimiento', on_delete=django.db.models.deletion.PROTECT, to='finanzas.office', verbose_name='Oficina')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caja_registrada', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['fecha'], name='finanzas_ca_fecha_1e053f_idx'), models.Index(fields=['tipo'], name='finanzas_ca_tipo_63dde9_idx'), models.Index(fields=['categoria'], name='finanzas_ca_categor_027459_idx'), models.Index(fields=['oficina', 'fecha', 'tipo'], name='finanzas_ca_oficina_88d951_idx')],
            },
        ),
    ]
