# Generated by Django 5.2.14 on 2026-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0008_cashmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='categoria',
            field=models.CharField(choices=[('convenio', 'Pago de convenio'), ('cliente', 'Pago de cliente'), ('anticipo', 'Anticipo'), ('devolucion', 'Devolución'), ('otro_ingreso', 'Otro ingreso'), ('papeleria', 'Papelería'), ('gasolina', 'Gasolina'), ('renta', 'Renta'), ('luz', 'Luz'), ('agua', 'Agua'), ('internet', 'Internet'), ('telefono', 'Teléfono'), ('viaticos', 'Viáticos'), ('comisiones', 'Comisiones'), ('honorarios', 'Honorarios'), ('otro_egreso', 'Otro egreso')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='categoria',
            field=models.CharField(choices=[('renta', 'Renta'), ('luz', 'Luz'), ('agua', 'Agua'), ('internet', 'Internet'), ('telefono', 'Teléfono'), ('papeleria', 'Papelería'), ('publicidad', 'Publicidad'), ('sueldos', 'Sueldos'), ('gasolina', 'Gasolina'), ('mantenimiento', 'Mantenimiento'), ('impuestos', 'Impuestos'), ('equipo', 'Equipo/Cómputo'), ('muebles', 'Muebles'), ('seguros', 'Seguros'), ('honorarios', 'Honorarios profesionales'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='settlementpayment',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('cheque', 'Cheque'), ('tarjeta_credito', 'Tarjeta de crédito'), ('tarjeta_debito', 'Tarjeta de débito'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Forma de pago'),
        ),
    ]
