# Generated by Django 5.2.14 on 2026-07-15 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0009_alter_cashmovement_categoria_alter_cashmovement_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('porcentaje_participacion', models.DecimalField(decimal_places=2, default=25.0, help_text='Porcentaje de utilidades que le corresponde (ej: 25.00 = 25%%)', max_digits=5, verbose_name='% de participación')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, help_text='Desmarca para desactivar sin eliminar', verbose_name='¿Activo?')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Socio',
                'verbose_name_plural': 'Socios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='WorkWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='Número de semana del año (1-52)', verbose_name='Número de semana')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Semana de Trabajo',
                'verbose_name_plural': 'Semanas de Trabajo',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['fecha_inicio', 'fecha_fin'], name='finanzas_wo_fecha_i_00ddaf_idx'), models.Index(fields=['estado'], name='finanzas_wo_estado_440098_idx')],
                'unique_together': {('numero', 'fecha_inicio')},
            },
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='semana',
            field=models.ForeignKey(blank=True, help_text='Semana a la que pertenece este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.workweek', verbose_name='Semana de trabajo'),
        ),
        migrations.AddField(
            model_name='expense',
            name='semana',
            field=models.ForeignKey(blank=True, help_text='Semana a la que pertenece este gasto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finanzas.workweek', verbose_name='Semana de trabajo'),
        ),
        migrations.CreateModel(
            name='PartnerLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('concepto', models.CharField(help_text='Breve descripción del préstamo', max_length=200, verbose_name='Concepto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('socio_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_destino', to='finanzas.partner', verbose_name='Socio que recibe (destino)')),
                ('socio_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_origen', to='finanzas.partner', verbose_name='Socio que presta (origen)')),
            ],
            options={
                'verbose_name': 'Préstamo entre Socios',
                'verbose_name_plural': 'Préstamos entre Socios',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['estado'], name='finanzas_pa_estado_7719b2_idx'), models.Index(fields=['socio_origen', 'estado'], name='finanzas_pa_socio_o_e76065_idx'), models.Index(fields=['socio_destino', 'estado'], name='finanzas_pa_socio_d_6b5c9b_idx')],
            },
        ),
    ]
