# Generated by Django 5.2.14 on 2026-07-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0014_tareaconciliacion'),
        ('finanzas', '0010_socios_semanas_prestamos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, help_text='Nombre de la empresa o persona con quien se firma el convenio', max_length=200, verbose_name='Empresa o contraparte')),
                ('fecha', models.DateField(verbose_name='Fecha del convenio')),
                ('monto_convenio', models.DecimalField(decimal_places=2, help_text='Monto total acordado en el convenio', max_digits=12, verbose_name='Monto del convenio')),
                ('honorarios', models.DecimalField(decimal_places=2, default=0, help_text='Suma total de honorarios generados (se calcula automáticamente al guardar)', max_digits=12, verbose_name='Honorarios totales')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de firma'), ('firmado', 'Firmado'), ('pagado', 'Pagado'), ('parcial', 'Pagado parcialmente'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas / Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente con quien se firma el convenio', on_delete=django.db.models.deletion.PROTECT, to='expedientes.cliente', verbose_name='Cliente')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenios_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('oficina', models.ForeignKey(help_text='Oficina responsable del convenio', on_delete=django.db.models.deletion.PROTECT, to='finanzas.office', verbose_name='Oficina')),
                ('responsable', models.ForeignKey(help_text='Abogado o asesor responsable del convenio', on_delete=django.db.models.deletion.PROTECT, related_name='convenios_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Honorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(choices=[(30.0, '30% (Tarifa general)'), (35.0, '35% (Tarifa especial)'), (40.0, '40% (Tarifa preferente)'), (25.0, '25% (Tarifa reducida)'), (50.0, '50% (Tarifa alta)')], decimal_places=2, default=30.0, help_text='Porcentaje de honorarios sobre el monto del convenio', max_digits=5, verbose_name='Porcentaje')),
                ('monto_calculado', models.DecimalField(decimal_places=2, editable=False, help_text='Calculado automáticamente: monto_del_convenio × porcentaje ÷ 100', max_digits=12, verbose_name='Monto calculado')),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de pago')),
                ('fecha_pagado', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='honorario_set', to='finanzas.agreement', verbose_name='Convenio')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='honorarios_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Honorario',
                'verbose_name_plural': 'Honorarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['fecha'], name='finanzas_ag_fecha_2f36dc_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['estado'], name='finanzas_ag_estado_26bfd6_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['oficina', 'fecha'], name='finanzas_ag_oficina_8064ec_idx'),
        ),
        migrations.AddIndex(
            model_name='agreement',
            index=models.Index(fields=['responsable', 'estado'], name='finanzas_ag_respons_11b4bb_idx'),
        ),
        migrations.AddIndex(
            model_name='honorario',
            index=models.Index(fields=['estado'], name='finanzas_ho_estado_7fd25e_idx'),
        ),
        migrations.AddIndex(
            model_name='honorario',
            index=models.Index(fields=['convenio', 'estado'], name='finanzas_ho_conveni_8fb2a1_idx'),
        ),
    ]
