# Generated by Django 5.2.14 on 2026-07-15 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0011_convenios_honorarios'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerUtilitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilidad_generada', models.DecimalField(decimal_places=2, default=0, help_text='Total de utilidad generada en distribuciones', max_digits=14, verbose_name='Utilidad generada')),
                ('utilidad_pagada', models.DecimalField(decimal_places=2, default=0, help_text='Total de utilidad que ya se le ha pagado al socio', max_digits=14, verbose_name='Utilidad pagada')),
                ('utilidad_pendiente', models.DecimalField(decimal_places=2, default=0, help_text='Utilidad generada pendiente de pago', max_digits=14, verbose_name='Utilidad pendiente')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='resumen_utilidades', to='finanzas.partner', verbose_name='Socio')),
            ],
            options={
                'verbose_name': 'Resumen de Utilidades del Socio',
                'verbose_name_plural': 'Resúmenes de Utilidades de Socios',
                'ordering': ['partner__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfitDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de distribución')),
                ('descripcion', models.CharField(blank=True, help_text='Breve descripción de la distribución', max_length=300, verbose_name='Descripción')),
                ('monto_convenio', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Monto del convenio')),
                ('honorarios', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Honorarios')),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Comisiones')),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, help_text='Retenciones fiscales aplicables', max_digits=12, verbose_name='Retenciones / ISR')),
                ('gastos_relacionados', models.DecimalField(decimal_places=2, default=0, help_text='Gastos operativos relacionados al convenio', max_digits=12, verbose_name='Gastos relacionados')),
                ('utilidad_neta', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Utilidad Neta')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('distribuida', 'Distribuida'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='borrador', max_length=15, verbose_name='Estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convenio', models.ForeignKey(help_text='Convenio que genera la distribución', on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones', to='finanzas.agreement', verbose_name='Convenio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distribuciones_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Distribución de Utilidad',
                'verbose_name_plural': 'Distribuciones de Utilidades',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de participación del socio en esta distribución', max_digits=5, verbose_name='% aplicado')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto calculado: utilidad_neta × porcentaje ÷ 100', max_digits=12, verbose_name='Monto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilidades', to='finanzas.partner', verbose_name='Socio')),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profits', to='finanzas.profitdistribution', verbose_name='Distribución')),
            ],
            options={
                'verbose_name': 'Participación de Socio',
                'verbose_name_plural': 'Participaciones de Socios',
                'ordering': ['partner__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='profitdistribution',
            index=models.Index(fields=['fecha'], name='finanzas_pr_fecha_93bf34_idx'),
        ),
        migrations.AddIndex(
            model_name='profitdistribution',
            index=models.Index(fields=['estado'], name='finanzas_pr_estado_4e0749_idx'),
        ),
        migrations.AddIndex(
            model_name='profitdistribution',
            index=models.Index(fields=['convenio', 'estado'], name='finanzas_pr_conveni_ebe7c3_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerprofit',
            index=models.Index(fields=['estado'], name='finanzas_pa_estado_b21af9_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerprofit',
            index=models.Index(fields=['partner', 'estado'], name='finanzas_pa_partner_20dc3c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='partnerprofit',
            unique_together={('distribucion', 'partner')},
        ),
    ]
