# Generated by Django 5.2.14 on 2026-06-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='puede_generar_documentos',
            field=models.BooleanField(default=False, help_text='Permite al usuario acceder al generador de demandas, machotes y documentos legales', verbose_name='¿Puede generar documentos legales?'),
        ),
    ]
