# Generated by Django 5.2.14 on 2026-06-03 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_puede_generar_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('cambio_rol', 'Cambio de Rol'), ('cambio_docs', 'Permiso de Documentos'), ('cambio_staff', 'Cambio Staff'), ('cambio_activo', 'Cambio Activo/Inactivo'), ('mixto', 'Cambio Múltiple')], max_length=20, verbose_name='Acción')),
                ('detalle', models.TextField(blank=True, help_text='Descripción de lo que cambió (ej: "Rol: asesor → admin")', verbose_name='Detalle del cambio')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha')),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('usuario_modificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificado')),
            ],
            options={
                'verbose_name': 'Auditoría de Permiso',
                'verbose_name_plural': 'Auditoría de Permisos',
                'ordering': ['-created_at'],
            },
        ),
    ]
