# Generated by Django 5.2.14 on 2026-06-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permisoauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisoauditlog',
            name='accion',
            field=models.CharField(choices=[('cambio_rol', 'Cambio de Rol'), ('cambio_docs', 'Permiso de Documentos'), ('mixto', 'Cambio Múltiple')], max_length=20, verbose_name='Acción'),
        ),
    ]
