# Generated by Django 5.2.14 on 2026-06-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_permisoauditlog_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('admin', 'Administrativo'), ('asesor', 'Asesor'), ('finanzas', 'Finanzas')], default='asesor', max_length=20, verbose_name='Rol'),
        ),
    ]
