# Generated by Django 5.2.14 on 2026-05-28 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('whatsapp', models.CharField(blank=True, max_length=15, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa/Patrón')),
                ('puesto', models.CharField(blank=True, max_length=100, verbose_name='Puesto')),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salario mensual')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida/despido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['curp'], name='expedientes_curp_314335_idx'), models.Index(fields=['nombre'], name='expedientes_nombre_95d1a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Número de expediente')),
                ('estado', models.CharField(choices=[('nuevo', '📄 Nuevo'), ('solicitud', '📨 Solicitud creada'), ('citatorio', '📬 Citatorio generado'), ('audiencia', '⚖️ Audiencia programada'), ('no_notificado', '❌ No notificado'), ('reprogramacion', '🔄 Reprogramación'), ('convenio', '🤝 Convenio'), ('sin_conciliacion', '🚫 Sin conciliación'), ('demanda', '⚡ Demanda'), ('cerrado', '✅ Cerrado')], default='nuevo', max_length=20, verbose_name='Estado')),
                ('monto_reclamado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto reclamado')),
                ('monto_convenio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto convenio')),
                ('fecha_audiencia', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de audiencia')),
                ('resultado_audiencia', models.CharField(blank=True, choices=[('no_notificado', 'No notificado'), ('convenio', 'Convenio alcanzado'), ('sin_conciliacion', 'Sin conciliación'), ('inasistencia', 'Inasistencia'), ('reprogramada', 'Reprogramada')], max_length=20, null=True, verbose_name='Resultado de audiencia')),
                ('tipo_despido', models.CharField(blank=True, choices=[('justificado', 'Despido justificado'), ('injustificado', 'Despido injustificado'), ('voluntario', 'Renuncia voluntaria'), ('rescision', 'Rescisión'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo de despido')),
                ('prestaciones_reclamadas', models.TextField(blank=True, verbose_name='Prestaciones reclamadas')),
                ('folio', models.CharField(blank=True, max_length=50, verbose_name='Folio de trámite')),
                ('fecha_tramite', models.DateField(blank=True, null=True, verbose_name='Fecha de trámite')),
                ('proxima_accion', models.DateField(blank=True, null=True, verbose_name='Próxima acción')),
                ('notas', models.TextField(blank=True, verbose_name='Notas internas')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=10, verbose_name='Prioridad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesor', models.ForeignKey(limit_choices_to={'profile__rol': 'asesor'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Asesor asignado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='expedientes.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'ordering': ['-created_at'],
                'permissions': [('puede_ver_todos_expedientes', 'Puede ver todos los expedientes')],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Archivo')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('ine', 'INE/Identificación'), ('contrato', 'Contrato laboral'), ('evidencia', 'Evidencia'), ('screenshot', 'Screenshot/Captura'), ('citatorio', 'Citatorio'), ('pdf', 'PDF/Documento'), ('otro', 'Otro')], default='pdf', max_length=20, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='expedientes.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('cambio_estado', 'Cambio de estado'), ('actualizacion', 'Actualización'), ('subida_documento', 'Subida de documento'), ('nota_agregada', 'Nota agregada'), ('resultado_audiencia', 'Resultado de audiencia')], max_length=30, verbose_name='Acción')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='expedientes.expediente', verbose_name='Expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_lista', to='expedientes.expediente', verbose_name='Expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['numero'], name='expedientes_numero_8251c9_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['estado'], name='expedientes_estado_3881ca_idx'),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['asesor'], name='expedientes_asesor__69f243_idx'),
        ),
    ]
