# Generated by Django 5.2.14 on 2026-05-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_calle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_colonia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Colonia / Ejido / Poblado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_cp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_actividad',
            field=models.CharField(blank=True, max_length=200, verbose_name='Actividad económica del patrón'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_calle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Calle (empresa)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_colonia',
            field=models.CharField(blank=True, max_length=200, verbose_name='Colonia (empresa)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_cp',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código Postal (empresa)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_numero',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número (empresa)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_razon_social',
            field=models.CharField(blank=True, max_length=200, verbose_name='Razón social / Nombre comercial'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_referencias',
            field=models.TextField(blank=True, verbose_name='Referencias del domicilio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='empresa_telefono',
            field=models.CharField(blank=True, max_length=15, verbose_name='Teléfono de la empresa'),
        ),
        migrations.CreateModel(
            name='SolicitudConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidad_sede', models.CharField(default='Tijuana', max_length=100, verbose_name='Unidad Sede')),
                ('fecha_solicitud', models.DateField(blank=True, null=True, verbose_name='Fecha de solicitud')),
                ('edad', models.PositiveIntegerField(blank=True, null=True, verbose_name='Edad')),
                ('fecha_conflicto', models.DateField(blank=True, null=True, verbose_name='Fecha del conflicto')),
                ('horas_semanales', models.PositiveIntegerField(blank=True, null=True, verbose_name='Horas semanales trabajadas')),
                ('periodo_pago', models.CharField(blank=True, choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal')], max_length=15, null=True, verbose_name='Periodo de pago')),
                ('objeto_despido', models.BooleanField(default=False, verbose_name='Despido')),
                ('objeto_terminacion_voluntaria', models.BooleanField(default=False, verbose_name='Terminación voluntaria')),
                ('objeto_antiguedad', models.BooleanField(default=False, verbose_name='Derecho de antigüedad')),
                ('objeto_rescision', models.BooleanField(default=False, verbose_name='Rescisión de la relación laboral')),
                ('objeto_prestaciones', models.BooleanField(default=False, verbose_name='Pago de prestaciones')),
                ('objeto_preferencia', models.BooleanField(default=False, verbose_name='Derecho de preferencia')),
                ('objeto_ascenso', models.BooleanField(default=False, verbose_name='Derecho de ascenso')),
                ('objeto_acoso', models.BooleanField(default=False, verbose_name='Acoso laboral')),
                ('citatorio_entrega', models.CharField(choices=[('solicitante', 'Solicitante'), ('notificador', 'El notificador del centro')], default='solicitante', max_length=20, verbose_name='Quién entregará el citatorio')),
                ('discapacidad_motriz', models.BooleanField(default=False, verbose_name='Discapacidad motriz')),
                ('discapacidad_visual', models.BooleanField(default=False, verbose_name='Discapacidad visual')),
                ('discapacidad_auditiva', models.BooleanField(default=False, verbose_name='Discapacidad auditiva')),
                ('discapacidad_psicosocial', models.BooleanField(default=False, verbose_name='Discapacidad psicosocial-cognitiva')),
                ('discapacidad_habla', models.BooleanField(default=False, verbose_name='Discapacidad habla o lenguaje')),
                ('requiere_traductor', models.BooleanField(default=False, verbose_name='Requiere traductor')),
                ('traductor_lengua', models.CharField(blank=True, max_length=100, verbose_name='Lengua de origen')),
                ('firma_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del firmante')),
                ('firma_fecha', models.DateField(blank=True, null=True, verbose_name='Fecha de firma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solicitud', to='expedientes.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Solicitud de Conciliación',
                'verbose_name_plural': 'Solicitudes de Conciliación',
            },
        ),
    ]
