# Generated by Django 5.2.14 on 2026-05-28 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_remove_cliente_direccion_cliente_direccion_calle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(help_text='Número con código de país, ej: +526641234567', max_length=20, verbose_name='Número destino')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('recordatorio_audiencia', '📅 Recordatorio de Audiencia'), ('citatorio', '📬 Citatorio'), ('convenio', '🤝 Seguimiento de Convenio'), ('seguimiento', '📞 Seguimiento'), ('documentos', '📎 Solicitud de Documentos'), ('personalizado', '💬 Mensaje Personalizado')], default='personalizado', max_length=30, verbose_name='Tipo')),
                ('via', models.CharField(choices=[('deep_link', 'Enlace wa.me'), ('twilio', 'API Twilio')], default='deep_link', max_length=15, verbose_name='Enviado vía')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('enviado', '✅ Enviado'), ('fallido', '❌ Fallido')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('link_generado', models.TextField(blank=True, help_text='Link wa.me generado para el mensaje', verbose_name='Link generado')),
                ('error_log', models.TextField(blank=True, verbose_name='Registro de error')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_mensajes', to='expedientes.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Mensaje WhatsApp',
                'verbose_name_plural': 'Mensajes WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
