# Generated by Django 5.2.14 on 2026-05-28 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_whatsappmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Legal 2024', max_length=100, verbose_name='Nombre de la configuración')),
                ('activo', models.BooleanField(default=True, help_text='Solo una configuración puede estar activa a la vez', verbose_name='Configuración activa')),
                ('uma_diaria', models.DecimalField(decimal_places=2, default=108.57, help_text='Valor de la UMA diaria (2024: $108.57)', max_digits=10, verbose_name='UMA diaria')),
                ('salario_minimo', models.DecimalField(decimal_places=2, default=248.93, help_text='Salario mínimo general diario (2024: $248.93)', max_digits=10, verbose_name='Salario mínimo general')),
                ('salario_minimo_frontera', models.DecimalField(decimal_places=2, default=374.89, help_text='Salario mínimo ZLF (2024: $374.89)', max_digits=10, verbose_name='Salario mínimo frontera')),
                ('aguinaldo_dias', models.PositiveIntegerField(default=15, help_text='Mínimo legal: 15 días', verbose_name='Días de aguinaldo')),
                ('prima_vacacional_porcentaje', models.DecimalField(decimal_places=2, default=25.0, help_text='Mínimo 25%', max_digits=5, verbose_name='% Prima vacacional')),
                ('prima_antiguedad_dias_por_ano', models.PositiveIntegerField(default=12, help_text='Normalmente 12 días por año', verbose_name='Días por año (prima antigüedad)')),
                ('tope_prima_tipo', models.CharField(choices=[('uma', '2 × UMA'), ('salario_minimo', '2 × Salario Mínimo'), ('frontera', '2 × Salario Mínimo Frontera')], default='uma', help_text='Tope salarial para prima de antigüedad', max_length=20, verbose_name='Tipo de tope')),
                ('tope_prima_multiplo', models.PositiveIntegerField(default=2, help_text='Normalmente 2 × UMA o 2 × SM', verbose_name='Múltiplo del tope')),
                ('indemnizacion_dias', models.PositiveIntegerField(default=90, help_text='3 meses = 90 días', verbose_name='Días de indemnización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Legal',
                'verbose_name_plural': 'Configuraciones Legales',
            },
        ),
        migrations.CreateModel(
            name='CalculoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_mensual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario mensual')),
                ('salario_diario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario diario calculado')),
                ('periodo_pago', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=20, verbose_name='Periodo de pago')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('fecha_salida', models.DateField(blank=True, null=True, verbose_name='Fecha de salida')),
                ('dias_trabajados', models.PositiveIntegerField(default=0, verbose_name='Días trabajados')),
                ('años_trabajados', models.DecimalField(decimal_places=4, default=0, max_digits=6, verbose_name='Años trabajados')),
                ('aguinaldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Aguinaldo proporcional')),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Vacaciones proporcionales')),
                ('dias_vacaciones', models.PositiveIntegerField(default=0, verbose_name='Días de vacaciones según antigüedad')),
                ('prima_vacacional', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prima vacacional')),
                ('prima_antiguedad', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prima de antigüedad')),
                ('tope_salarial_aplicado', models.BooleanField(default=False, verbose_name='Tope salarial aplicado')),
                ('indemnizacion', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Indemnización constitucional')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total prestaciones')),
                ('recalculado_en', models.DateTimeField(blank=True, null=True, verbose_name='Último recálculo')),
                ('notas', models.TextField(blank=True, help_text='Anotaciones del asesor sobre este cálculo', verbose_name='Notas del cálculo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expediente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo_laboral', to='expedientes.expediente', verbose_name='Expediente')),
            ],
            options={
                'verbose_name': 'Cálculo Laboral',
                'verbose_name_plural': 'Cálculos Laborales',
            },
        ),
    ]
