# Generated by Django 5.2.14 on 2026-06-03 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_legalconfig_calculolaboral'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del machote')),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción de cuándo usar esta plantilla', verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('demanda', '⚡ Demanda Laboral'), ('carta_finiquito', '📄 Carta Finiquito'), ('convenio', '🤝 Convenio'), ('solicitud', '📋 Solicitud'), ('citatorio', '📬 Citatorio'), ('otro', '📎 Otro')], default='demanda', max_length=30, verbose_name='Categoría')),
                ('tipo_despido', models.CharField(blank=True, choices=[('justificado', 'Despido justificado'), ('injustificado', 'Despido injustificado'), ('voluntario', 'Renuncia voluntaria'), ('rescision', 'Rescisión'), ('otro', 'Otro')], help_text='Solo para demandas: el tipo de despido al que aplica', max_length=20, null=True, verbose_name='Tipo de despido')),
                ('jurisdiccion', models.CharField(choices=[('federal', 'Federal'), ('estatal', 'Estatal (Baja California)'), ('ambas', 'Ambas')], default='federal', max_length=20, verbose_name='Jurisdicción')),
                ('contenido_html', models.TextField(help_text='HTML de la plantilla. Usa marcadores como {{ nombre }}, {{ empresa }}, etc.', verbose_name='Contenido HTML')),
                ('icono', models.CharField(default='📄', help_text='Emoji o icono para mostrar en la UI', max_length=10, verbose_name='Icono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el selector', verbose_name='Orden')),
                ('archivo_origen', models.CharField(blank=True, help_text='Nombre del archivo .docx del que se importó', max_length=255, verbose_name='Archivo de origen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Machote',
                'verbose_name_plural': 'Machotes',
                'ordering': ['categoria', 'orden', 'nombre'],
            },
        ),
    ]
