# Generated by Django 5.2.14 on 2026-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_machote'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='asesoria_gratuita_agendada',
            field=models.BooleanField(default=False, help_text='El cliente agendó una fecha para la asesoría gratuita', verbose_name='Asesoría agendada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='asesoria_gratuita_ofrecida',
            field=models.BooleanField(default=False, help_text='Al cliente se le ofreció la asesoría gratuita semanal', verbose_name='Asesoría gratuita ofrecida'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_asesoria_gratuita',
            field=models.DateField(blank=True, help_text='Fecha programada para la asesoría gratuita', null=True, verbose_name='Fecha de asesoría gratuita'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['fecha_asesoria_gratuita'], name='expedientes_fecha_a_ee6dc0_idx'),
        ),
    ]
