# Generated by Django 5.2.14 on 2026-06-03 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_cliente_asesoria_gratuita_agendada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('contenido', models.TextField(blank=True, help_text='Detalles del aviso o pendiente', verbose_name='Contenido')),
                ('prioridad', models.CharField(choices=[('alta', '🔴 Alta'), ('media', '🟡 Media'), ('baja', '🟢 Baja')], default='media', max_length=10, verbose_name='Prioridad')),
                ('activo', models.BooleanField(default=True, help_text='Desmarca para ocultar el aviso', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Aviso / Pendiente',
                'verbose_name_plural': 'Avisos y Pendientes',
                'ordering': ['-prioridad', '-created_at'],
            },
        ),
    ]
