# Generated by Django 5.2.14 on 2026-06-03 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0007_aviso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(help_text='Explica por qué necesitas transferir el caso (ej: conflicto de horario, audiencia simultánea, etc.)', verbose_name='Motivo de la transferencia')),
                ('estado', models.CharField(choices=[('pendiente', '⏳ Pendiente'), ('aprobada', '✅ Aprobada'), ('rechazada', '❌ Rechazada'), ('cancelada', '🔙 Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('comentario_admin', models.TextField(blank=True, help_text='Nota del admin al aprobar/rechazar', verbose_name='Comentario del administrador')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asesor_asignado', models.ForeignKey(blank=True, limit_choices_to={'profile__rol': 'asesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asesor asignado (reasignación)')),
                ('asesor_destino', models.ForeignKey(blank=True, help_text='Puedes sugerir un asesor específico o dejarlo vacío para que administración lo asigne', limit_choices_to={'profile__rol': 'asesor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Asesor destino (opcional)')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_transferencia', to='expedientes.expediente', verbose_name='Expediente')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelto por')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transferencias_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante (asesor actual)')),
            ],
            options={
                'verbose_name': 'Solicitud de Transferencia',
                'verbose_name_plural': 'Solicitudes de Transferencia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado'], name='expedientes_estado_9f2e84_idx'), models.Index(fields=['expediente', 'estado'], name='expedientes_expedie_0580d2_idx')],
            },
        ),
    ]
