# Generated by Django 5.2.14 on 2026-06-03 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0008_solicitudtransferencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('tipo', models.CharField(choices=[('transferencia', '🔄 Transferencia'), ('aviso', '📢 Aviso'), ('sistema', '⚙️ Sistema'), ('recordatorio', '⏰ Recordatorio')], default='sistema', max_length=20, verbose_name='Tipo')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('link', models.CharField(blank=True, help_text='URL opcional a la que lleva la notificación', max_length=500, verbose_name='Enlace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'leida'], name='expedientes_usuario_8a95b0_idx')],
            },
        ),
    ]
