# Generated by Django 5.2.14 on 2026-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0009_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='prioridad',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('solicitud', 'Solicitud creada'), ('citatorio', 'Citatorio generado'), ('audiencia', 'Audiencia programada'), ('no_notificado', 'No notificado'), ('reprogramacion', 'Reprogramación'), ('convenio', 'Convenio'), ('sin_conciliacion', 'Sin conciliación'), ('demanda', 'Demanda'), ('cerrado', 'Cerrado')], default='nuevo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='machote',
            name='categoria',
            field=models.CharField(choices=[('demanda', 'Demanda Laboral'), ('carta_finiquito', 'Carta Finiquito'), ('convenio', 'Convenio'), ('solicitud', 'Solicitud'), ('citatorio', 'Citatorio'), ('otro', 'Otro')], default='demanda', max_length=30, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('aviso', 'Aviso'), ('sistema', 'Sistema'), ('recordatorio', 'Recordatorio')], default='sistema', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='solicitudtransferencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido')], default='pendiente', max_length=15, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='tipo',
            field=models.CharField(choices=[('recordatorio_audiencia', 'Recordatorio de Audiencia'), ('citatorio', 'Citatorio'), ('convenio', 'Seguimiento de Convenio'), ('seguimiento', 'Seguimiento'), ('documentos', 'Solicitud de Documentos'), ('personalizado', 'Mensaje Personalizado')], default='personalizado', max_length=30, verbose_name='Tipo'),
        ),
    ]
