# Generated by Django 5.2.14 on 2026-06-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0010_alter_aviso_prioridad_alter_expediente_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='notificar_whatsapp_auto',
            field=models.BooleanField(default=True, help_text='Enviar mensajes automáticos al cliente cuando cambia el estado del expediente', verbose_name='Notificaciones WhatsApp automáticas'),
        ),
    ]
