# Generated by Django 5.2.14 on 2026-06-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0011_expediente_notificar_whatsapp_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='machote',
            name='favorito',
            field=models.BooleanField(default=False, help_text='Los machotes favoritos aparecen primero en el editor', verbose_name='Favorito'),
        ),
    ]
