# Generated by Django 5.2.14 on 2026-07-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0012_machote_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='genero',
            field=models.CharField(choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], default='masculino', max_length=10, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='horas_semanales',
            field=models.PositiveIntegerField(blank=True, default=40, help_text='Horas trabajadas por semana', null=True, verbose_name='Horas semanales'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='jornada',
            field=models.CharField(choices=[('diurna', 'Diurna'), ('nocturna', 'Nocturna'), ('mixta', 'Mixta')], default='diurna', help_text='Tipo de jornada laboral', max_length=10, verbose_name='Jornada'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='periodo_pago',
            field=models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', help_text='¿Cada cuándo le pagan?', max_length=10, verbose_name='Periodo de pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_persona_citado',
            field=models.CharField(choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral')], default='fisica', help_text='¿El patrón es persona física o moral?', max_length=10, verbose_name='Tipo de persona del patrón'),
        ),
    ]
