# Generated by Django 5.2.14 on 2026-07-15 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0013_cliente_fecha_nacimiento_cliente_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ejecutando', 'Ejecutando'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('folio', models.CharField(blank=True, max_length=50, verbose_name='Folio generado')),
                ('pdf_path', models.CharField(blank=True, max_length=500, verbose_name='Ruta del PDF')),
                ('error', models.TextField(blank=True, verbose_name='Error')),
                ('detalle', models.TextField(blank=True, verbose_name='Detalle')),
                ('screenshots_json', models.TextField(blank=True, help_text='Lista de rutas de screenshots en formato JSON', verbose_name='Capturas (JSON)')),
                ('modo', models.CharField(choices=[('automatico', 'Automático (Headless)'), ('debug', 'Visible (Debug)')], default='automatico', max_length=15, verbose_name='Modo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada en')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_conciliacion', to='expedientes.expediente', verbose_name='Expediente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Iniciada por')),
            ],
            options={
                'verbose_name': 'Tarea de Conciliación',
                'verbose_name_plural': 'Tareas de Conciliación',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado'], name='expedientes_estado_32db2a_idx'), models.Index(fields=['expediente', 'estado'], name='expedientes_expedie_1b1846_idx')],
            },
        ),
    ]
