# Generated by Django 5.2.14 on 2026-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0014_tareaconciliacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='como_supo',
            field=models.CharField(blank=True, choices=[('facebook', 'Facebook / Instagram'), ('google', 'Google / Internet'), ('recomendacion', 'Recomendación'), ('whatsapp', 'WhatsApp'), ('tiktok', 'TikTok'), ('tv_radio', 'Televisión / Radio'), ('volante', 'Volante / Folleto'), ('otro', 'Otro')], help_text='¿Cómo se enteró el cliente de Conciliación Laboral Tijuana?', max_length=20, verbose_name='¿Cómo supo de nosotros?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='oficina',
            field=models.CharField(blank=True, choices=[('plaza_patria', 'Plaza Patria'), ('plaza_patria_abajo', 'Plaza Patria Abajo'), ('otay', 'Otay')], help_text='¿Cuál oficina atendió al cliente?', max_length=30, verbose_name='Oficina que atendió'),
        ),
    ]
